### ISSUE TITLE
clearer instructions needed

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/astropi-ndvi#20]
URL: /en/projects/astropi-ndvi/0

Hi! First of all, thank you for sharing this project. I look forward to getting it done.
 
It'd be helpful to add a few notes on system requirements, and the time it may take to install some of the necessary packages.

eg. I thought the Pi Zero 2 could handle OpenCV, however, if it does manage to build the wheel for opencv-python, it'll take at least 12 hours.

**Comment by libxx1** [comment]
Hi @MarcScott , this feedback came in through the project site. I'm not sure if any changes should be made to the intro to specify the range of Raspberry Pi that can be used or if the time expectancies need adding in for those using the Zero range. Can you take a look and see if you think this is an issue that requires project amendment please.

**Comment by MarcScott** [comment]
I've ordered a pi zero 2 w to test this, but I doubt it takes 12 hours.

**Comment by MarcScott** [comment]
Okay, I tested on a Zero 2 W and it took a few seconds. Then tested on a new lite OS, and it took at most a minute. Without further details I can't really see the issue. If I can get an email address I can ask, but my guess is they're running either an old version of Raspbian with Python 2 installed, they've manually installed a very new version of Python, or they're using the 64 bit OS. None of these are supported by pywheels, and will result in building from source, which I can confirm will take hours.
Going to close this for now, but if you have contact details, I'll be happy to investigate this further.
